import type { SiteSettingsView } from '@/types/types';

export const defaultSiteSettings: SiteSettingsView = {
  id: 1,
  siteTitle: '',
  siteTitleEn: null,
  siteDescription: '',
  siteDescriptionEn: null,
  favicon: '',
  logo: '',
  ogImage: '',
  keywords: '',
  keywordsEn: null,
  author: '',
  contactHeader: 'Kontakt',
  contactHeaderEn: null,
  contactEmail: '',
  contactLocation: '',
  contactPhone: '',
  formHeader: 'Kontaktní formulář',
  formHeaderEn: null,
  formNameLabel: 'Jméno',
  formNameLabelEn: null,
  formEmailLabel: 'Váš mail',
  formEmailLabelEn: null,
  formMessageLabel: 'Zpráva',
  formMessageLabelEn: null,
  formSubmitLabel: 'Odeslat',
  formSubmitLabelEn: null,
};
