import type { SiteSettingsView } from '@/types/types';

export const defaultSiteSettings: SiteSettingsView = {
  id: 1,
  siteTitle: '',
  siteTitleEn: null,
  siteDescription: '',
  siteDescriptionEn: null,
  favicon: '',
  logo: '',
  ogImage: '',
  keywords: '',
  keywordsEn: null,
  author: '',
  contactHeader: 'Kontakt',
  contactHeaderEn: 'Contact',
  contactEmail: '',
  contactLocation: '',
  contactPhone: '',
  formHeader: 'Kontaktní formulář',
  formHeaderEn: 'Contact form',
  formNameLabel: 'Jméno',
  formNameLabelEn: 'Name',
  formEmailLabel: 'Váš mail',
  formEmailLabelEn: 'Your email',
  formMessageLabel: 'Zpráva',
  formMessageLabelEn: 'Message',
  formSubmitLabel: 'Odeslat',
  formSubmitLabelEn: 'Send',
};
